# test_calculator.py

# Assert statements
# https://docs.python.org/3/library/unittest.html#unittest.TestCase.debug

# python3 -m unittest test_calculator.py

import unittest
import calculator as calc

class TestCalculator(unittest.TestCase):  #test class
    
    # methods
    def test_add(self):  
        self.assertEqual(calc.add(10, 5), 15)
        self.assertEqual(calc.add(-1, 1), 0)  # boundary cases
        self.assertEqual(calc.add(-1, -1), -2)
        self.assertEqual(calc.add(-1.3, -1.2), -2.5)

    def test_subtract(self):
        self.assertEqual(calc.subtract(10, 5), 5)
        self.assertEqual(calc.subtract(-1, 1), -2)
        self.assertEqual(calc.subtract(-1, -1), 0)
        self.assertEqual(calc.subtract(-1.3, -1.2), -0.1)

    def test_multiply(self):
        self.assertEqual(calc.multiply(10, 5), 50)
        self.assertEqual(calc.multiply(-1, 1), -1)
        self.assertEqual(calc.multiply(-1, -1), 1)
    
    def test_divide(self):
        self.assertEqual(calc.divide(10, 5), 2)
        self.assertEqual(calc.divide(-1, 1), -1)
        self.assertEqual(calc.divide(-1, -1), 1)
        self.assertEqual(calc.divide(5, 2), 2.5)

        self.assertRaises(ValueError, calc.divide, 10, 0)
    

if __name__ == '__main__':
    unittest.main()